# Nadi Furkan Açıkgöz, 20170808059 Exercise Answers

# 9 Numpy

## Generate matrices A, with random Gaussian entries, B, a Toeplitz matrix, where A ∈ R ^ n×m and B ∈ R ^ m×m, for n = 200, m = 500.
### Exercise 9.1: Matrix operations
### Calculate A + A, AA^T, A^TA and AB. Write a function that computes A(B − λI) for any λ.

In [21]:
import numpy as np
# Because there was not a method to create Toeplitz matrix in numpy, I had to import toeplitz method in scipy library.
from scipy.linalg import toeplitz 


n,m = 2,5
# random.normal draws random samples from Gaussian distribution.
A = np.random.normal(3, 1.1, size=(n, m))
# Toeplitz matrix is the matrix which all the elements of the diagonal are the same. 
B = toeplitz(np.random.rand(1,m))

print(f"-> A + A: \n{A+A}\n")
print(f"-> A * A^T: \n{A.dot(A.transpose())}\n")
print(f"-> A^T * A: \n{A.transpose().dot(A)}\n")
print(f"-> A * B: \n{A.dot(B)}\n")

# A(B − λI)
def compute(A,B,lambda_):
    # Creating the same length of row of lambda_ as identity matrix for multiplication.
    I = np.identity(len(lambda_))
    lambda_.dot(I)
    result = B - lambda_
    return A.dot(result)

# lambda_ matrix can also be created using random library. For simplicity I used arrange method.
lambda_ = np.arange(len(B)*len(B)).reshape(len(B),len(B))
print(f'-> A(B - λI): \n{compute(A,B,lambda_)}')



-> A + A: 
[[ 5.72009556  6.25464644  3.56701121  8.5564804   8.9998411 ]
 [ 2.45396987  6.26351739 12.32589471  3.60396228  3.99598107]]

-> A * A^T: 
[[59.6935402  40.99501519]
 [40.99501519 56.53442683]]

-> A^T * A: 
[[ 9.68536532 12.78691456 12.66275481 14.44697508 15.32149205]
 [12.78691456 19.58806303 24.87846244 19.02281001 20.32993024]
 [12.66275481 24.87846244 41.16281234 18.73578028 20.33914401]
 [14.44697508 19.02281001 18.73578028 21.55047522 22.85208224]
 [15.32149205 20.32993024 20.33914401 22.85208224 24.24125112]]

-> A * B: 
[[8.36566996 6.9306705  6.45781856 7.16410583 7.68609311]
 [5.59874197 7.06239917 4.91223054 7.11261112 5.05469708]]

-> A(B - λI): 
[[-179.27801616 -197.26205297 -214.28394226 -230.12669234 -246.1537424 ]
 [-138.67905281 -151.53705827 -168.00888955 -180.13017163 -196.50974832]]


### Exercise 9.2: Solving a linear system
### Generate a vector b with m entries and solve Bx = b.

In [24]:
from numpy import linalg as LA

b = np.arange(m)

# We assume that matrix B is invertable to solve the equation. We multiply the inverse of B for the both side of equation.
inv_B = LA.inv(B)
x = b.dot(inv_B)
print(x)

[ -1.51622277 -23.24107645   1.73497186  25.56033727   2.20763715]


### Exercise 9.3: Norms
### Compute the Frobenius norm of A: ||A||_F and the infinity norm of B: ||B||_∞. Also find the largest and smallest singular values of B.

In [25]:
fro_A = LA.norm(A, 'fro')

def inf_norm(B):
    return max(abs(row.sum()) for row in B)

inf_B = inf_norm(B)

print(f'Frobenius norm of A: {fro_A}')
print(f'Infinity norm of B: {inf_B}')
# s is the array of singular values of matrix B.
u, s, vh = LA.svd(B)
print(f'max singular value: {s.max()} min singular value: {s.min()}')

Frobenius norm of A: 10.780907523211708
Infinity norm of B: 2.2714438782336943
max singular value: 2.1853516176473455 min singular value: 0.05771357240645074


### Exercise 9.6: Nearest neighbor
### Write a function that takes a value z and an array A and finds the element in A that is closest to z. The function should return the closest value, not index.
### Hint: Use the built-in functionality of Numpy rather than writing code to find this value manually. In particular, use brackets and argmin.

In [56]:
# The idea here is that subtracting the value z from every element in array A to find the differences. And using the argmin()
# function to find the smalles difference.
def nearest_neighbor(z,A):
    # Here we take the absolute value of difference for preventing negative values.
    absolute_difference = np.abs(A - z)
    return A[absolute_difference.argmin()]

print(nearest_neighbor(8, np.array([1,2,3,5,2,12,23,4,9,67])))

9
